const data = [
  {
    id: 1,
    brand: "Mobil",
    name: "DTE 10 Excel 100",
    sku: "130833",
    sizesAvailable: true,
    price: 22.99,
    viscosity: "0W-20",
    sizeOptions: [
      "1 Quart",
      "1 Gallon",
      "Bulk 1 Drum",
      "Bulk 1 Tote",
      "Half-Quart",
    ],
  },
  {
    id: 2,
    brand: "Mobil",
    name: "DTE 10 Excel 100",
    sku: "130834",
    sizesAvailable: true,
    price: 26.22,
    viscosity: "0W-20",
    sizeOptions: [
      "1 Quart",
      "1 Gallon",
      "Bulk 1 Drum",
      "Bulk 1 Tote",
      "Half-Quart",
    ],
  },
  {
    id: 3,
    brand: "Mobil",
    name: "DTE 10 Excel 100",
    sku: "130835",
    sizesAvailable: true,
    price: 28.44,
    viscosity: "10W-30",
    sizeOptions: ["1 Gallon", "Bulk 1 Drum", "Bulk 1 Tote", "Half-Quart"],
  },
  {
    id: 4,
    brand: "Mobil",
    name: "DTE 10 Excel 100",
    sku: "130836",
    sizesAvailable: true,
    price: 23.33,
    viscosity: "5W-20",
    sizeOptions: ["1 Quart", "5 Quarts", "1 Gallon"],
  },
  {
    id: 5,
    brand: "Mobil",
    name: "DTE 10 Excel 200",
    sku: "130837",
    sizesAvailable: true,
    price: 25.5,
    viscosity: "0W-20",
    sizeOptions: [
      "1 Quart",
      "5 Quarts",
      "1 Gallon",
      "Bulk 1 Drum",
      "Bulk 1 Tote",
      "Half-Quart",
    ],
  },
  {
    id: 6,
    brand: "Mobil",
    name: "DTE 10 Excel 200",
    sku: "130838",
    sizesAvailable: true,
    price: 25.5,
    viscosity: "5W-20",
    sizeOptions: [
      "1 Quart",
      "5 Quarts",
      "1 Gallon",
      "Bulk 1 Drum",
      "Bulk 1 Tote",
      "Half-Quart",
    ],
  },
  {
    id: 7,
    brand: "Mobil",
    name: "DTE 10 Excel 200",
    sku: "130839",
    sizesAvailable: true,
    price: 25.5,
    viscosity: "5W-30",
    sizeOptions: [
      "1 Quart",
      "5 Quarts",
      "1 Gallon",
      "Bulk 1 Drum",
      "Bulk 1 Tote",
      "Half-Quart",
    ],
  },
  {
    id: 8,
    brand: "Mobil",
    name: "DTE 10 Excel 200",
    sku: "130840",
    sizesAvailable: true,
    price: 25.5,
    viscosity: "10W-40",
    sizeOptions: [
      "1 Quart",
      "5 Quarts",
      "1 Gallon",
      "Bulk 1 Drum",
      "Bulk 1 Tote",
      "Half-Quart",
    ],
  },
  {
    id: 9,
    brand: "Old World",
    name: "Helix Ultra 5W-40",
    sku: "140001",
    sizesAvailable: true,
    price: 30.0,
    viscosity: "5W-40",
    sizeOptions: ["Half Quart", "5 Quarts", "1 Gallon", "Bulk 1 Drum"],
  },
  {
    id: 10,
    brand: "Old World",
    name: "Helix Ultra 5W-30",
    sku: "140002",
    sizesAvailable: true,
    price: 28.0,
    viscosity: "5W-30",
    sizeOptions: ["Half Quart", "5 Quarts", "1 Gallon", "Bulk 1 Drum"],
  },
  {
    id: 11,
    brand: "Peak",
    name: "EDGE 0W-20",
    sku: "150001",
    sizesAvailable: true,
    price: 32.99,
    viscosity: "0W-20",
    sizeOptions: ["Half Quart", "5 Quarts", "1 Gallon", "Bulk 1 Drum"],
  },
  {
    id: 12,
    brand: "Peak",
    name: "EDGE 5W-20",
    sku: "150002",
    sizesAvailable: true,
    price: 34.99,
    viscosity: "5W-20",
    sizeOptions: ["Half Quart", "5 Quarts", "Bulk 1 Drum", "Bulk 1 Tote"],
  },
  {
    id: 13,
    brand: "Peak",
    name: "SynPower 5W-30",
    sku: "160001",
    sizesAvailable: true,
    price: 29.5,
    viscosity: "5W-30",
    sizeOptions: ["1 Quart", "5 Quarts", "Bulk 1 Drum"],
  },
  {
    id: 14,
    brand: "Peak",
    name: "SynPower 0W-20",
    sku: "160002",
    sizesAvailable: true,
    price: 27.99,
    viscosity: "0W-20",
    sizeOptions: ["1 Quart", "5 Quarts", "Bulk 1 Drum", "Bulk 1 Tote"],
  },
  {
    id: 15,
    brand: "Old World",
    name: "Delo 400 XLE 10W-40",
    sku: "170001",
    sizesAvailable: true,
    price: 35.0,
    viscosity: "10W-40",
    sizeOptions: ["1 Gallon", "Bulk 1 Drum"],
  },
  {
    id: 16,
    brand: "Old World",
    name: "Delo 400 XLE 5W-30",
    sku: "170002",
    sizesAvailable: true,
    price: 33.0,
    viscosity: "5W-30",
    sizeOptions: ["1 Gallon", "Bulk 1 Drum", "Bulk 1 Tote"],
  },
  {
    id: 17,
    brand: "Mobil",
    name: "Super 3000 5W-30",
    sku: "130841",
    sizesAvailable: true,
    price: 26.99,
    viscosity: "5W-30",
    sizeOptions: ["1 Quart", "5 Quarts", "Bulk 1 Drum"],
  },
  {
    id: 18,
    brand: "Mobil",
    name: "Super 3000 0W-20",
    sku: "130842",
    sizesAvailable: true,
    price: 24.99,
    viscosity: "0W-20",
    sizeOptions: ["1 Quart", "5 Quarts", "Bulk 1 Drum"],
  },
  {
    id: 19,
    brand: "Peak",
    name: "Quartz 9000 5W-20",
    sku: "180001",
    sizesAvailable: true,
    price: 31.0,
    viscosity: "5W-20",
    sizeOptions: ["1 Liter", "5 Liters", "Bulk 1 Drum", "Bulk 1 Tote"],
  },
  {
    id: 20,
    brand: "Peak",
    name: "Quartz 9000 10W-30",
    sku: "180002",
    sizesAvailable: true,
    price: 29.0,
    viscosity: "10W-30",
    sizeOptions: ["1 Liter", "5 Liters", "Bulk 1 Drum", "Bulk 1 Tote"],
  },
];

export default data;
